name: Conditional Example

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building..."

  dev-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'  # Condition for this job to run

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy
        run: echo " DevDeploying..."

  prod-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Condition for this job to run

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy
        run: echo " DevDeploying..."
