name: display current time every 3 hrs

on:
  schedule:
    - cron: '1 * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print current time every 3 hrs
        run: echo "Current time:$(date)"
             TESTVAR="SUCCESS"
             echo $TESTVAR
