name: Maven CI/CD

on:
  #workflow_dispatch:
 push:
    branches: [ maven ]
  #pull_request:
    #branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build project with Maven
      run: mvn -B package --file pom.xml

    - run: mkdir staging && cp target/*jar-with-dependencies.jar staging
    
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging
 
    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: copy files to S3 bucket
      run: |
          aws s3 cp staging/Package "s3://gleanup-s3/"
        
