on: push
name: build
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "MY_DATE=$(date +%Y%m%d%H%M)" 
      - name: Run Test
        run: echo "Hello"
