on: push
name: build
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Display current date
        run: echo "Current Date:$(date)"
      - name: Run Test
        run: echo "Hello"
