name: Secret key

on:
  workflow_dispatch: 
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
    
    steps:
      - name: Print current time every 3 hrs        
        run:  |  
            echo "Current time:$(date)"
            echo ${{ vars.TESTVAR }}
            echo ${{ vars.DAY_OF_THE_WEEK }}
            echo "M_Secret_Key:${{ secrets.M_Secret_Key }}"
      
     
